## Sentitment by Finetuning Bert model

### Data Preprocessing

In [3]:
import os
import re
from tqdm import tqdm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
# Download data
import requests
request = requests.get("https://drive.google.com/uc?export=download&id=1wHt8PsMLsfX5yNSqrt2fSTcb8LEiclcf")
with open("data.zip", "wb") as file:
    file.write(request.content)

# Unzip data
import zipfile
with zipfile.ZipFile('data.zip') as zip:
    zip.extractall('data')

In [5]:
 # Load data and set labels
data_complaint = pd.read_csv('data/complaint1700.csv')
data_complaint['label'] = 0
data_non_complaint = pd.read_csv('data/noncomplaint1700.csv')
data_non_complaint['label'] = 1

# Concatenate complaining and non-complaining data
data = pd.concat([data_complaint, data_non_complaint], axis=0).reset_index(drop=True)

# Drop 'airline' column
data.drop(['airline'], inplace=True, axis=1)

# Display 5 random samples
print(list(data.head(5)['tweet']))
print(list(data.head(5)['label']))
data.sample(5)

["@united I'm having issues. Yesterday I rebooked for 24 hours after I was supposed to fly, now I can't log on &amp; check in. Can you help?", "@united kinda feel like the $6.99 you charge for in flight Wi-Fi is ridiculous. AND it sucks, slow, or doesn't work. #anythingtomakeabuck", 'Livid in Vegas, delayed, again&amp; again&amp;again, @SouthwestAir decided to cancel a flight and combine two, then waited on crew, now pilots.', '@united the most annoying man on earth is on my flight. what can you do to help me?', "@united The last 2 weeks I've flown wit u, you have given me 4 reasons to convince me it was a bad decision. Time 2 go back 2 @SouthwestAir"]
[0, 0, 0, 0, 0]


id                                              tweet  label
627    38466  Oh @JetBlue why hast thou forsaken us?? It was...      0
2386   62611  @MaksimC @united what's the problem. I'm w Pro...      1
178   154120  “@JustinNFJK: Guys I would totally fight...      0
1976   24256  @JLJeffLewis @AmericanAir @USAirways @Jennipul...      1
521    73089  @AmericanAir Your Baggage Customer Service des...      0

In [6]:
data.count()

id       3400
tweet    3400
label    3400
dtype: int64

In [7]:
max_tweet_length = max([len(each) for each in list(data['tweet'])])
max_tweet_length

187

In [8]:
from sklearn.model_selection import train_test_split

X = data.tweet.values
y = data.label.values

X_train, X_val, y_train, y_val =\
    train_test_split(X, y, test_size=0.1, random_state=2022)

In [9]:
# Load test data
test_data = pd.read_csv('data/test_data.csv')

# Keep important columns
test_data = test_data[['id', 'tweet']]

# Display 5 samples from the test data
test_data.sample(5)

id                                              tweet
899   35663  @AmericanAir let's continue this discussion......
1252  49247  @united I get that sometimes there's things yo...
828   33067  @AmericanAir  what does priority mean? Clearly...
2530  96817  Just had a very bad experience with the disser...
911   36275  18 1/2 hours later. Finally heading home. Wors...

In [10]:
max_tweet_length = max([len(each.split(' ')) for each in list(test_data['tweet'])])
max_tweet_length

32

### Bert model finetuning

In [1]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

pretrained_bert_model_name = 'distilbert-base-uncased'
pretrained_bert_tokenizer = AutoTokenizer.from_pretrained(pretrained_bert_model_name)

In [11]:
from datasets import Dataset

def prepare_classification_labels(samples):
    inputs = pretrained_bert_tokenizer(samples['tweet'], truncation=True, padding='max_length', max_length=32, is_split_into_words=False)
    
    # print('inputs', inputs)
    # print('inputs', inputs.keys())
    
    return inputs

train_datasets = Dataset.from_pandas(data[:300]).map(prepare_classification_labels, batched=True, batch_size=100).remove_columns(['id', 'tweet'])
validation_datasets = Dataset.from_pandas(data[300:340]).map(prepare_classification_labels, batched=True, batch_size=10).remove_columns(['id', 'tweet'])

Parameter 'function'=<function prepare_classification_labels at 0x298051c10> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.


  0%|          | 0/3 [00:00<?, ?ba/s]

  0%|          | 0/4 [00:00<?, ?ba/s]

In [ ]:
pretrained_bert_model = AutoModelForSequenceClassification.from_pretrained(pretrained_bert_model_name, num_labels=2, id2label={0:'negative', 1:'positive'}, label2id={'negative':0, 'positive':1})

In [82]:
from transformers import TrainingArguments, Trainer
import torch 

device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')   # mps is for Apple M1 GPU
device

device(type='mps')

In [83]:
from transformers import EarlyStoppingCallback

args = TrainingArguments(
    output_dir='./sentiment_test_model',
    per_device_train_batch_size=32,
    per_device_eval_batch_size=4,
    num_train_epochs=10,
    logging_strategy='steps',
    evaluation_strategy='steps',
    eval_steps = 10,
    load_best_model_at_end=True,
    report_to='none'
)

    
trainer = Trainer(
    model=pretrained_bert_model,
    args=args,
    train_dataset=train_datasets,
    eval_dataset=validation_datasets,
    tokenizer=pretrained_bert_tokenizer,
    callbacks = [EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()
trainer.save_model()

PyTorch: setting up devices
torch.distributed process group is initialized, but local_rank == -1. In order to use Torch DDP, launch your script with `python -m torch.distributed.launch
***** Running training *****
  Num examples = 300
  Num Epochs = 10
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 100


***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4
***** Running Evaluation *****
  Num examples = 40
  Batch size = 4


Training completed. Do not forget to share your model on huggingface.co/models =)


Saving model checkpoint to ./sentiment_test_model
Configuration saved in ./sentiment_test_model/config.json
Model weights saved in ./sentiment_test_model/pytorch_model.bin
tokenizer config file saved in ./sentiment_test_model/tokenize

## Restaurant ASC(Aspect based Sentiment Classification)

### Preprocess training data

In [12]:
import json
import pandas as pd

rest_asc_training_file = '/Users/sean.huang/Documents/my/books and courses/ztgg/Shared Code/BERT-for-ABSA/asc/rest/train.json'
rest_asc_training_samples = json.load(open(rest_asc_training_file))
len(rest_asc_training_samples)

3452

In [13]:
rest_asc_training_samples['1592_0']

{'polarity': 'positive',
 'term': 'server',
 'id': '1592_0',
 'sentence': 'Our server was very helpful and friendly.'}

In [14]:
dict_rest_asc_training_samples = {'sample_id':[], 'sentence':[], 'term':[], 'label':[]}

for key in rest_asc_training_samples.keys():
    dict_rest_asc_training_samples['sample_id'].append(key)
    dict_rest_asc_training_samples['sentence'].append(rest_asc_training_samples[key]['sentence'])
    dict_rest_asc_training_samples['term'].append(rest_asc_training_samples[key]['term'])
    dict_rest_asc_training_samples['label'].append(0 if rest_asc_training_samples[key]['polarity'] == 'negative' else 1 if rest_asc_training_samples[key]['polarity'] == 'positive' else 2)
    
# dict_rest_asc_training_samples

In [15]:
df_rest_asc_training_samples = pd.DataFrame.from_dict(dict_rest_asc_training_samples)
df_rest_asc_training_samples

sample_id                                           sentence  \
0       1592_0          Our server was very helpful and friendly.   
1       1940_1  Super friendly and knowledgable staff, fabulou...   
2       1940_0  Super friendly and knowledgable staff, fabulou...   
3       1940_3  Super friendly and knowledgable staff, fabulou...   
4       1940_2  Super friendly and knowledgable staff, fabulou...   
...        ...                                                ...   
3447    3139_2  Where tanks in other Chinatown restaurants dis...   
3448    3139_1  Where tanks in other Chinatown restaurants dis...   
3449    3139_0  Where tanks in other Chinatown restaurants dis...   
3450    2818_0  This was my frist time at Cafe St. Bart's and ...   
3451    2818_1  This was my frist time at Cafe St. Bart's and ...   

             term  label  
0          server      1  
1           staff      1  
2     jazz brunch      1  
3       live jazz      1  
4     bistro fare      1  
...           ...    ...  
3447        tanks      0  
3448      dim sum      2  
3449        tanks      1  
3450      service      1  
3451         food      1  

[3452 rows x 4 columns]

In [16]:
max_sent_length = max([len(each.split(' ')) for each in list(df_rest_asc_training_samples['sentence'])])
max_sent_length

69

In [17]:
from collections import Counter
Counter(df_rest_asc_training_samples['label'])

Counter({1: 2094, 0: 779, 2: 579})

### Load and finetune pretrained Bert model

In [18]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

pretrained_bert_model_name = 'distilbert-base-uncased'
pretrained_bert_tokenizer = AutoTokenizer.from_pretrained(pretrained_bert_model_name)

In [19]:
tokens = pretrained_bert_tokenizer(list(df_rest_asc_training_samples['sentence'])[0], is_split_into_words=False)
tokens

{'input_ids': [101, 2256, 8241, 2001, 2200, 14044, 1998, 5379, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [20]:
sentence1 = list(df_rest_asc_training_samples['sentence'])[0]
term1 = list(df_rest_asc_training_samples['term'])[0]
sentence1, term1

('Our server was very helpful and friendly.', 'server')

In [21]:
tokens = pretrained_bert_tokenizer(sentence1, term1, is_split_into_words=False)
tokens

{'input_ids': [101, 2256, 8241, 2001, 2200, 14044, 1998, 5379, 1012, 102, 8241, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [22]:
tokens = pretrained_bert_tokenizer(sentence1, term1, truncation=True, padding='max_length', max_length=16, is_split_into_words=False)
tokens

{'input_ids': [101, 2256, 8241, 2001, 2200, 14044, 1998, 5379, 1012, 102, 8241, 102, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]}

In [23]:
from datasets import Dataset

def prepare_asc_classification_labels(samples):
    inputs = pretrained_bert_tokenizer(samples['sentence'], samples['term'], truncation=True, padding='max_length', max_length=128, is_split_into_words=False)
    
    # print('inputs', inputs)
    # print('inputs', inputs.keys())
    
    return inputs

asc_train_datasets = Dataset.from_pandas(df_rest_asc_training_samples[:3000]).map(prepare_asc_classification_labels, batched=True, batch_size=1000).remove_columns(['sample_id', 'sentence', 'term'])
asc_validation_datasets = Dataset.from_pandas(df_rest_asc_training_samples[3000:]).map(prepare_asc_classification_labels, batched=True, batch_size=100).remove_columns(['sample_id', 'sentence', 'term'])

  0%|          | 0/3 [00:00<?, ?ba/s]

  0%|          | 0/5 [00:00<?, ?ba/s]

In [24]:
asc_train_datasets

Dataset({
    features: ['label', 'input_ids', 'attention_mask'],
    num_rows: 3000
})

In [25]:
asc_validation_datasets

Dataset({
    features: ['label', 'input_ids', 'attention_mask'],
    num_rows: 452
})

In [26]:
import torch 

device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')   # mps is for Apple M1 GPU
device

device(type='mps')

In [27]:
from transformers import TrainingArguments, Trainer, DataCollatorForTokenClassification
import torch

pretrained_bert_model = AutoModelForSequenceClassification.from_pretrained(pretrained_bert_model_name, num_labels=3, id2label={0:'negative', 1:'positive', 2:'neutral'}, label2id={'negative':0, 'positive':1, 'neutral':2})

pretrained_bert_model.to(device)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_transform.bias', 'vocab_transform.weight', 'vocab_layer_norm.bias', 'vocab_layer_norm.weight', 'vocab_projector.bias', 'vocab_projector.weight']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias', 'pre_classifier

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0): TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
       

In [28]:
import numpy as np
from datasets import load_metric
metric = load_metric('accuracy')
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [29]:
from transformers import EarlyStoppingCallback

args = TrainingArguments(
    output_dir='./rest_asc_model_distilbert',
    per_device_train_batch_size=128,
    per_device_eval_batch_size=16,
    num_train_epochs=20,
    logging_strategy='steps',
    logging_steps=25,
    evaluation_strategy='steps',
    eval_steps = 25,
    load_best_model_at_end=True,
    metric_for_best_model='eval_accuracy',
    report_to='none'
)
    
trainer = Trainer(
    model=pretrained_bert_model,
    args=args,
    train_dataset=asc_train_datasets,
    eval_dataset=asc_validation_datasets,
    tokenizer=pretrained_bert_tokenizer,
    compute_metrics=compute_metrics,
    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)]
)

trainer.train()
trainer.save_model()

torch.distributed process group is initialized, but local_rank == -1. In order to use Torch DDP, launch your script with `python -m torch.distributed.launch
/Users/sean.huang/miniconda3/envs/m1_new/lib/python3.9/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 3000
  Num Epochs = 20
  Instantaneous batch size per device = 128
  Total train batch size (w. parallel, distributed & accumulation) = 128
  Gradient Accumulation steps = 1
  Total optimization steps = 480


***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evaluation *****
  Num examples = 452
  Batch size = 16
***** Running Evalua

### Load finetune Bert model for Rest NER task, and do prediction

In [30]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

finetuned_rest_asc_tokenizer = AutoTokenizer.from_pretrained('./rest_asc_model_distilbert')
finetuned_rest_asc_model = AutoModelForSequenceClassification.from_pretrained('./rest_asc_model_distilbert', num_labels=3)

Didn't find file ./rest_asc_model_distilbert/added_tokens.json. We won't load it.
loading file ./rest_asc_model_distilbert/vocab.txt
loading file ./rest_asc_model_distilbert/tokenizer.json
loading file None
loading file ./rest_asc_model_distilbert/special_tokens_map.json
loading file ./rest_asc_model_distilbert/tokenizer_config.json
loading configuration file ./rest_asc_model_distilbert/config.json
Model config DistilBertConfig {
  "_name_or_path": "./rest_asc_model_distilbert",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "id2label": {
    "0": "negative",
    "1": "positive",
    "2": "neutral"
  },
  "initializer_range": 0.02,
  "label2id": {
    "negative": 0,
    "neutral": 2,
    "positive": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "problem_type": "single_label_clas

In [31]:
sentiment_labels = finetuned_rest_asc_model.config.id2label
sentiment_labels

{0: 'negative', 1: 'positive', 2: 'neutral'}

In [32]:
import numpy as np
tokens = finetuned_rest_asc_tokenizer('very terrible service, price is high, but taste is good.', is_split_into_words=False)

output = finetuned_rest_asc_model(torch.tensor([tokens['input_ids']]))
print('Logits:', output.logits)
print('Sentiment: ', sentiment_labels[np.argmax(output.logits.tolist())])

Logits: tensor([[ 2.0011,  1.2939, -2.8973]], grad_fn=<AddmmBackward0>)
Sentiment:  negative


In [33]:
tokens = finetuned_rest_asc_tokenizer('very terrible service, price is high, but taste is good.', 'service', is_split_into_words=False)

output = finetuned_rest_asc_model(torch.tensor([tokens['input_ids']]))
print('Logits:', output.logits)
print('Sentiment: ', sentiment_labels[np.argmax(output.logits.tolist())])

Logits: tensor([[ 4.7387, -1.7003, -2.8472]], grad_fn=<AddmmBackward0>)
Sentiment:  negative


In [34]:
tokens = finetuned_rest_asc_tokenizer('very terrible service, price is high, but taste is good.', 'price', is_split_into_words=False)
output = finetuned_rest_asc_model(torch.tensor([tokens['input_ids']]))
print('Logits:', output.logits)
print('Sentiment: ', sentiment_labels[np.argmax(output.logits.tolist())])

Logits: tensor([[ 4.7166, -1.5648, -2.8783]], grad_fn=<AddmmBackward0>)
Sentiment:  negative


In [35]:
tokens = finetuned_rest_asc_tokenizer('very terrible service, price is high, but taste is good.', 'taste', is_split_into_words=False)
output = finetuned_rest_asc_model(torch.tensor([tokens['input_ids']]))
print('Logits:', output.logits)
print('Sentiment: ', sentiment_labels[np.argmax(output.logits.tolist())])

Logits: tensor([[-2.2771,  5.2422, -2.5211]], grad_fn=<AddmmBackward0>)
Sentiment:  positive


### Evaluation

In [36]:
rest_asc_test_file = '/Users/sean.huang/Documents/my/books and courses/ztgg/Shared Code/BERT-for-ABSA/asc/rest/test.json'
rest_asc_test_samples = json.load(open(rest_asc_test_file))
len(rest_asc_test_samples)

1120

In [37]:
def asc(sentence, term):

    tokens = finetuned_rest_asc_tokenizer(sentence, term, is_split_into_words=False)
    output = finetuned_rest_asc_model(torch.tensor([tokens['input_ids']]))
    
    return sentiment_labels[np.argmax(output.logits.tolist())]

asc('very terrible service, price is high, but taste is good.', 'taste')

'positive'

In [38]:
y_pred = []
y_true = []

for key in rest_asc_test_samples.keys():
    y_pred.append(asc(rest_asc_test_samples[key]['sentence'], rest_asc_test_samples[key]['term']))
    # print(rest_asc_test_samples[key]['sentence'])
    # print(rest_asc_test_samples[key]['term'])
    # print(asc(rest_asc_test_samples[key]['sentence'], rest_asc_test_samples[key]['term']))
    y_true.append(rest_asc_test_samples[key]['polarity'])
    

In [39]:
print(y_true[:10], y_true[:10])
print(y_pred[:10], y_pred[:10])

['positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative'] ['positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative']
['positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative'] ['positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative']


In [40]:
Counter(y_true)

Counter({'positive': 728, 'negative': 196, 'neutral': 196})

In [41]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_true, y_pred, labels=['negative', 'positive', 'neutral'])

(array([0.78217822, 0.87279597, 0.7016129 ]),
 array([0.80612245, 0.95192308, 0.44387755]),
 array([0.79396985, 0.91064389, 0.54375   ]),
 array([196, 728, 196]))

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true, y_pred, labels=['negative', 'positive', 'neutral'])

array([[158,  19,  19],
       [ 17, 693,  18],
       [ 27,  82,  87]])

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.8375

## Home Work: do laptop ASC

## Load Testing

### Config File

### Result - Distil Bert

### Result - Bert

### Config File

### Result - Distil Bert

### Result - Bert